---
title: "Calibration analysis" 
author: "Dezheng Huo: plot <5% & >99%" 
date: '2025-07-3'
fontsize: 9pt
output:
  word_document: default
  html_document:
    fig_caption: true
    df_print: paged
  pdf_document: default
header-includes: \usepackage{pdfpages}
geometry: margin=0.5in
fig_crop: no
---

```{r setup, include=FALSE}
#Load package
library(data.table)
library(readr)
library(dplyr)
library("tidyverse")
library(iCARE)
library(table1)
library(pROC)
library(ROCnReg)
library(readxl)
library(ggplot2)
## library(emmeans)
```

### Reading PRS scores and calcute the observed and theoritical OR
```{r plot1, echo=TRUE, message=FALSE, warning=FALSE, fig.height=4.75, fig.width=4}

PRSvalid = "G:/BCAC/james.li/PRS_AABCG/output/ARISK_FAMH_SCORE_OUTPUT"
PRSvalidA = "G:/BCAC/james.li/PRS_AABCG/output/CALIBRATION_FINAL_SCORE_OUTPUT"

subtype_vec = c("OVERALL", "ERPOS", "ERNEG", "TNBC")
subtype_label = c("overall BC", "ER+", "ER-", "TNBC")
Black_vec = c("PROPTUNE_ALLSUBTYPE", "ENSEMBLE_FSS", "ENSEMBLE_GLMNET", "XANCESTRY_PRSICE2") 
White_vec = c("EUR_313_ALL_SNP", "EUR_313_ALL_SNP", "EUR_313_ALL_SNP", "EUR_330_ALL_SNP") 
AUC_vec <- cbind(c(0.612, 0.621, 0.610, 0.639), c(0.630, 0.641, 0.601, 0.636)) 
AUC_vec

for (j in 1:2){
  for (i in 1:4){
    cat("--------------------------------------------------------------------")
    cat("\n") 
    if (j==1){
      cat(paste("Black PRS model", "for", subtype_vec[i], "\n"))
      plot_title = paste0("African ancestry PRS for ", subtype_label[i]) 
      filename_B <- paste0(PRSvalid, "/", subtype_vec[i], "_", Black_vec[i], ".sscore")
      cat(paste0(filename_B, "\n"))
      scores_current = fread(filename_B, header=T)
      if (i==1) {
        phenodata <- read_excel("G:/AABCG/data/AABCG_pheno_clean_Jan2023_share.xlsx") 
        phenodata1 <- phenodata %>% filter(ER!=9 & PR!=9 & HER2!=9) %>% 
          rename("#IID" = "AABCGS_ID...1") %>%
          select("#IID")
        scores_current <- inner_join(scores_current, phenodata1, by="#IID")
        }
      }
    if (j==2){
      cat(paste0("White PRS model", "\n")) 
      filename_W <- paste0(PRSvalidA, "/", subtype_vec[i], "/", subtype_vec[i], "_", White_vec[i], ".sscore")
      cat(paste0(filename_W, "\n"))
      scores_current <- fread(filename_W, header=T)
      plot_title = paste0("European ancestry PRS for ", subtype_label[i])       
    }
    
######################################
# computing odds ratio by SD         #
######################################  
  control_SD <- sd(as.data.frame(scores_current)[scores_current$Status==0, "SCORE"])
  scores_current$score_SD <- scores_current$SCORE/control_SD

cat("\n") 
cat(paste0("MODEL 1: OR per SD", "\n"))
  reg1 <- glm(Status ~ score_SD + Age + as.factor(Platform) + PC1+PC2+PC3+PC4+PC5+PC6+PC7+PC8+PC9+PC10, 
              data = scores_current, family = "binomial")
  # print(summary(reg1)) 
  # print(exp(cbind(Odds_Ratio = coef(reg1), confint(reg1)))) 
  cat("\n")

# preparing confidence interval of OR
logOR_sd <- summary(reg1)$coefficients["score_SD","Estimate"]
se_logOR_sd <- summary(reg1)$coefficients["score_SD","Std. Error"]
logOR_sd_CI_95_lower_sd <- logOR_sd - qnorm(.975)*se_logOR_sd
logOR_sd_CI_95_upper_sd <- logOR_sd + qnorm(.975)*se_logOR_sd
# outputting results
OR_SD_STR <- paste0("OR per SD: ", sprintf("%.3f",exp(logOR_sd)), ", 95% CI: ", sprintf("%.3f",exp(logOR_sd_CI_95_lower_sd)), ", ", sprintf("%.3f",exp(logOR_sd_CI_95_upper_sd)))
print(OR_SD_STR)
cat("\n") 

######################################
# computing odds ratio by percentile #
######################################
cat(paste0("MODEL 2: OR per percentile", "\n"))
# computing percentiles in control group participants
percentiles <- c(5, 10, 20, 40, 60, 80, 90, 95)
perc.u <-c(0, percentiles)/100
perc.v <- c(perc.u[-1], 1)

cov_validation3 <- scores_current %>% filter(Status == 0) 
cutoffs <- quantile(cov_validation3$SCORE, probs = percentiles / 100)
cat(paste("Cutoffs:", "\n"))  
print( cutoffs ) 
cat("\n")

##labels <- c("<=5%", "5-10%", "10-20%", "20-40%", "40-60%", "60-80%", "80-90%", "90-95%", ">95%") 
labels <- paste0(perc.u*100, "-", perc.v*100, "%")
# Use `cutoffs` to categorize
scores_current$score_cut <- cut(
  scores_current$SCORE,
  breaks = c(-Inf, cutoffs, Inf),
  labels = labels,
  include.lowest = TRUE,
  right = TRUE
)
print(table(scores_current$score_cut, scores_current$Status)) 

scores_current$score_cut <- relevel(scores_current$score_cut, ref = "40-60%")

reg2 <- glm(Status ~ score_cut + Age + as.factor(Platform) + PC1+PC2+PC3+PC4+PC5+PC6+PC7+PC8+PC9+PC10, 
              data = scores_current, family = "binomial")
   #print(summary(reg2)) 
   #print(exp(cbind(Odds_Ratio = coef(reg2), confint(reg2)))) 
cat("\n") 
      
# calculate confidence interval of OR
logOR <- summary(reg2)$coefficients[(1:length(percentiles))+1,"Estimate"]
se_logOR <- summary(reg2)$coefficients[(1:length(percentiles))+1,"Std. Error"]
logOR_CI_95_lower <- logOR - qnorm(.975)*se_logOR
logOR_CI_95_upper <- logOR + qnorm(.975)*se_logOR
OR_obs <- cbind(OR=exp(logOR), OR_L=exp(logOR_CI_95_lower), OR_U=exp(logOR_CI_95_upper)) 
OR_obs1 <- rbind(OR_obs[1:(nrow(OR_obs)/2), ], c(1,1,1), OR_obs[(nrow(OR_obs)/2+1):nrow(OR_obs), ]) 
  
 # Calculate theoretical OR
   sigma =  qnorm(AUC_vec[i, j]) * sqrt(2)
   cat(paste("SD in control:", control_SD, "\n")) 
   cat(paste("log OR per SD in AABCG:", logOR_sd, "\n")) 
   cat(paste("sigma from AUC", sigma, "\n"))

  # Calculate odds ratio
  OR_theo <- (0.6 - 0.4) * (pnorm(qnorm(1 - perc.u) + sigma) - pnorm(qnorm(1 - perc.v) + sigma)) / 
    (perc.v - perc.u) / (pnorm(qnorm(0.6) + sigma) - pnorm(qnorm(0.4) + sigma)) 

  OR_95CI <- cbind(OR_theo, OR_obs1)
  rownames(OR_95CI) <- labels
  cat("\n") 
  print(OR_95CI)
  cat("\n") 

  plot1 <- ggplot(OR_95CI, aes(x = OR_theo, y = OR)) +
  geom_point(size = 3, color="blue") +
  geom_errorbar(aes(ymin = OR_L, ymax = OR_U), color="blue", width = 0.02) +
  geom_line(data = OR_95CI, aes(x=OR_theo, y=OR_theo, group = 1), linetype="dashed", color="maroon", linewidth=0.8) +
  scale_y_log10(
    breaks = c(0.3, 0.5, 1, 2, 3, 4),
    labels = c("0.3", "0.5", "1", "2", "3", "4")) +
  scale_x_log10(
    breaks = OR_theo,
    labels = c("<=5", "5-10", "10-20", "20-40", "40-60", "60-80", "80-90", "90-95", ">95")) +
  labs(
    title = plot_title,
    y = "Odds ratio (log scale)",
    x = "Percentile of PRS"
  ) +
  theme_minimal()  +
#  coord_fixed(ratio = 0.85) +     
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(panel.grid.minor = element_blank(),   
        axis.line = element_line(color = "black")) 
  
  ## inside a loop so need to explicitly print the plot 
  print(plot1)  
  
  }
} 
 

```



